### ISSUE TITLE
Converting from GL-reps to CPU-reps in background threads

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#1001]
When a background thread requests a CPU representation on data where only a GL representation is available, the GL->CPU converter will automatically try to download the data from the GPU. This will fail or have unexpected behavior if no GL context is activated for the current thread. 
The discussions in #348 suggested activating a local context in the call to the dispatch on processor level. While this works, it has to be done in every processor that does processing on RAM representations which is, by evidence, very easy to miss. In many cases, a CPU representation is available but in some cases, when the data has been generated on the GPU, it is not.  For example if a volume been passed through a `LowPassFilter` or similar processor. 

Issue #994 recently got reported where this issue appeared in `VolumeLaplacianProcessor`. 
I just had the same issue in the `VolumeSubsample` processor. 
The old issue #348 has the same causation.

**Comment by petersteneteg** [comment]
This has been evolving code kind of. Currently the when one submits code to run on a different thread one has to call `activateLocalContext`. Since that has usually only been done by very "advanced" users that has not been a big problem. But now running in the background is quite a bit easier with pool processors etc the problem will be more common. 
One solution for the use of volumes would be to always call `activateLocalContext` in the data representation converter function. The problem with this that is only solves the problem in some of the cases in all the other ones one still has to call `activateLocalContext` manually. Then it would work in some cases and not in others, which I believe will be even worse. 
So as I see it the best we can to is to try and document/teach the use of `activateLocalContext` better?
But if anyone has a more consistent solution it would be very welcome! 

One Ide might be to add some debug checks / asserts that we have a context activated and with a nice message of how to activate one?

**Comment by petersteneteg** [comment]
I have added assert in the FBO to make the errors more obvious. The PoolProcessor also handles the activation of context automatically so as long as one uses that it should just work....
