### ISSUE TITLE
multithreaded processor invalidation

### ISSUE THREAD

**Issue by TheHugeManatee** [inviwo/inviwo#1163]
Hi all,

I'm trying to implement a processor that does work on a separate thread (in this case, integration for a network protocol) and then asynchronously outputs new data from the processor. 

I thought that the way to go would be something like:
 - worker/IO thread receives new data and stores a temporary reference when new data is complete
 - worker/IO thread invalidates processor
 - processor reads temporary reference and pushes it into the out port

However, from the looks of `Processor::invalidate`, it is a synchronous call, meaning that with above approach some of the processor network will be executed on the worker thread which leads to all kinds of problems.

Directly updating the out port from the worker thread kind of works, but will lead to the rest of the network not updating unless there is another invalidation, for example while interacting with the view at the same time I can see the updated data.

So, is this a design oversight or if not, what would be the correct way to solve this? Is there another way to asynchronously invalidate the processor that I'm not seeing? Any help is much appreciated!

**Comment by ResearchDaniel** [comment]
Implementing threaded work is surprisingly difficult. Luckily,  we have a done the work for you :) 
I think that you are looking for the PoolProcessor
https://github.com/inviwo/inviwo/blob/master/include/inviwo/core/processors/poolprocessor.h

An example can be found here (search for PoolProcessor for more examples)

https://github.com/inviwo/inviwo/blob/master/modules/base/include/modules/base/processors/distancetransformram.h

**Comment by petersteneteg** [comment]
If you are doing networking, and not task based background work, the PoolProcessor might not be the best fit. It is most suitable for submitting task to the thread pool and then eventually outputting the result. 

If you have a network worker thread running concurrently you are probably better of not using the PoolProcessor. To invalidate the processor when you have new data you have to call invalidate in the main GUI thread as you noticed. What you can do in your background jobb it so call `dispatchFront` https://github.com/inviwo/inviwo/blob/5a23de833ba3f7bd56d71154e75df3bfc6ee6a7c/include/inviwo/core/common/inviwoapplication.h#L499-L514
That will push a job to eventually be run in the GUI thread. You can for example invalidate your processor here. A bit care has to be taken though to ensure that you are not referencing anything that might have been deleted while the task was waiting to be run in the GUI thread though, like for example your processor. I can provide more help with how to do that if you go down that road.

**Comment by TheHugeManatee** [comment]
thank you both for your quick feedback! I had a look at the `PoolProcessor`, and tried it but it makes the IGTL networking implementation a bit more complicated when only working with jobs.

the `dispatchFront` approach looks promising though! I was generally able to make it work, however, I would be interested in your ideas on how to best monitor the processor lifetime. I tried waiting for the future returned by `dispatchFront` in the destructor to ensure all related gui thread jobs have finished, but that seemed to deadlock.

right now i'm passing a shared pointer to an atomic flag into the job lambda, and set the flag in the destructor, and while it seemingly works, it doesn't really feel like the most elegant of solutions so if you have an alternative pattern i'd be interested!

**Comment by petersteneteg** [comment]
Unfortunately Inviwo's design is somewhat lacking in this aspect, there are a few quite invasive changes that would be needed to make this work in a nice way, maybe someday... I usually use a combination of a shared ptr and a week ptr, to ensure that the processor is still around. Usually I have some the processor own a shared ptr to some shared state and then I pass on a week ptr to that shared state into the background functor. And then the background functor will pass it on to the dispatchFront functor which will try and lock the week ptr to get the shared ptr. Then if the shared state refers to the processor for example I know that is fine because the processor should only be deleted on the main thread which we are now running on since the dispachFront call so it is fine to call Invalidate etc. Should not be much difference with this solution and the one with the atomic flag you suggested above. But in most cases I will anyway want to pass one some shared state with data, so then I can just as well take advantage of the shared ptr to do the synchronization to....

If all our processor where handled as shared ptr them selfs this would be much easier since we could just pass a week_ptr of the processor to the background job directly, unfortunately the processors are not shared ptrs at the and changing that is a non trivial refactoring at this point, although it might be worthwhile. And there might also be unforeseen consequences if processor are not actually deleted when they are removed from the network.

**Comment by petersteneteg** [comment]
I'll close this for now, pls reopen if you run into more issues
