### ISSUE TITLE
Camera interaction hickup when pressing non-picking area + releasing on (web) picking area

### ISSUE THREAD

**Issue by ResearchDaniel** [inviwo/inviwo#1218]
**Steps to reproduce**
1. Load Test workspaces->WebBrowser->web-property-sync.inv
2. Press volume, rotate, and release button on top of any picking area (GUI)
3. Press to rotate the volume again -> resulting in a jerky motion

**What happens** 
After pressing the volume its corresponding trackball expects a mouse release event to arrive at some point. 
However, when releaseing the mouse over a picking-area it will take presedence over the regular events (see line 192 in canvasopenglwidget.cpp, `CanvasQOpenGLWidget::propagateEvent(Event* e, Outport* source)`). 
Thus, if the picking event is handled it will not be forwarded as a regular event and the trackball will never get the mouse button release event. 

The image below shows event logs when pressing a non-picking area and then releasing the button on a web component. Press and release events are highlighted in yellow. 
<img width="1149" alt="picking" src="https://user-images.githubusercontent.com/8738140/140663228-b36cd981-797a-458f-a879-f10fa6f6b0b9.PNG">

**Some thoughts**
In some way one could think that the picking object should not mark the event as used, but the picked object could also do something with the event that made it valid to mark it as used (e.g. indicating a hovering).

It would make sense if the object that handled the press also got the release event. However, I do not think we have a mechanism for that currently?

Can we handle this special case in a graceful way?
Do we want to incorporate a special case similar to when the user releases the mouse outside of the window?

**Comment by ResearchDaniel** [comment]
@martinfalk You might have experience this one as well

**Comment by martinfalk** [comment]
Handling drag events is tricky, in particular since we have multiple mechanisms (regular mouse interaction events + picking events). Here, I would blame the web UI for not handling the events properly.  The GL UI handles correctly, I think. This is done by accepting a button release only if it has the same picking ID as when the button was first pressed as well as considering a delta to distinguish between a move and a click.

https://github.com/inviwo/inviwo/blob/512ba3ccc320b93beecf895cffb9b39e7f7ffef8/include/inviwo/core/interaction/events/pickingevent.h#L117-L129

> In some way one could think that the picking object should not mark the event as used, but the picked object could also do something with the event that made it valid to mark it as used.

This won't work if for example one uses picking also for clicking on things.

**Comment by ResearchDaniel** [comment]
Ok, I will check out the GL UI and see if that logic can be incorporated

**Comment by ResearchDaniel** [comment]
Thanks for the hint @martinfalk 
I think that resolves the problem. first will only be true if the pressed picking id belongs to the object
```
  if (p->getPressedLocalPickingId().first) {
      host_->SendMouseClickEvent(cefMouseEvent, type, mouseUp, clickCount);
      p->markAsUsed();
  }
```

**Comment by martinfalk** [comment]
That sounds like a reasonable fix.
