### ISSUE TITLE
util::KeepTrueWhileInScope is broken

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#204]
When using `util::KeepTrueWhileInScope`, the bool value is set to `true`. But in the destructor the bool value is set to `false` independent of the previous state.

https://github.com/inviwo/inviwo/blob/2e1c41a9d1209dfa5fb9ea91928167eca1381754/include/inviwo/core/util/raiiutils.h#L40-L47

**Comment by r-englund** [comment]
This is what is was designed to do. To set the value to true when created and to false when destroyed.

**Comment by martinfalk** [comment]
yeah, but what if it is used on the same variable twice in the same block? e.g. #203

**Comment by petersteneteg** [comment]
I would tend to agree with r-englund here. Seems unwise to use it in a nested fashion. But I don't have a strong opinion either way. But changing this behaviour need quite heavy testing, since we use it quite a lot, especially in the serialisation. And we have used it with this behaviour for many years...

**Comment by martinfalk** [comment]
Unwise yes. But you cannot always guarantee that this does not happen when using callbacks.
