### ISSUE TITLE
Color Scale Legend - Alpha Values are ignored from TF

### ISSUE THREAD

**Issue by MutterOberin** [inviwo/inviwo#784]
**Issue**

TFs alpha values are not used when legend is set to "No Background". Would be cool to have this.

![image](https://user-images.githubusercontent.com/11873547/69725845-6dae0180-111f-11ea-8927-789bc5bb6563.png)

**Comment by ResearchDaniel** [comment]
That was originally by design since it meant that you could not see the colors and that it mixed with the background (changed colors)

**Comment by r-englund** [comment]
> 
> 
> That was originally by design since it meant that you could not see the colors and that it mixed with the background (changed colors)

That should be an option!

**Comment by ResearchDaniel** [comment]
The one who needs it is most welcome to contribute. I don’t think it should be on by default as it means most colors won’t be visible for the tfs we use in volume rendering (we tried it)

**Comment by r-englund** [comment]
was it fixed?

**Comment by petersteneteg** [comment]
This is clearly not an issue, but rather a possible feature, although I agree with Daniel. We tried it with using transparency but for cases like above that is useless since the opacity for a tf used for raycasting is mostly way to low to be visible in the image.
Anyway this is a feature request and should not be in the issue system
