### ISSUE TITLE
PortInspector broken for vector<Mesh> outport

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#98]
**To Reproduce:**
Use SurfaceExtraction processor with one input volume and connected outport. Hover outport.

**Result**
DataTraits<Mesh>::info fails: the data vector has one element which is empty.

**Comment by petersteneteg** [comment]
@martinfalk  Im not able to repoduce this....

**Comment by r-englund** [comment]
The SurfaceExtraction outputs a vector of meshes

**Comment by petersteneteg** [comment]
yes, the issue was for a vector of meshes... but where the mesh is emtpy maybe?

**Comment by martinfalk** [comment]
@petersteneteg try `boron.inv`, add a surface extraction and connect it to `Volume Source` and `Mesh Renderer`. With the default settings, the surface extraction creates a vector with a single `shared_ptr<Mesh>` which is `nullptr`.

**Comment by martinfalk** [comment]
Potentially, a valid Mesh should be created by the surface extraction even though it is empty. But passing on a `nullptr` in the vector is dangerous.

**Comment by r-englund** [comment]
I think the problem is that we resize the output vector (https://github.com/inviwo/inviwo/blob/master/modules/base/processors/surfaceextraction.cpp#L110 ) which init entries to nullptr, they are nullptr until the surface extraction is completed in a background thread. 
Should we create a "copy" of that vector to put on the port containing only the valid meshes. Or will that have other side effects (same mesh have different indices on different network evaluations)

**Comment by petersteneteg** [comment]
Ohh, thats ugly, we set the data on the port *before* it's created....

**Comment by petersteneteg** [comment]
fixed the surface extraction and the DataInfo...
